name: squirrel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - python=3.10
  - snakemake-minimal=7.32
  - matplotlib>=3.3.1
  - gofasta
  - iqtree>=2.1
  - jclusterfunk>=0.0.25
