name: squirrel
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython>=1.74
  - minimap2>=2.16
  - python=3.10
  - snakemake-minimal
  - matplotlib
  - gofasta
  - iqtree>=2.1
  - jclusterfunk>=0.0.25
  - r-base>=4.2
  - r-tidyverse
  - bioconductor-ggtree
  - r-plotly
  - r-ape